rm(list=(ls()))
source("./R/counties_population_download.R")
source("./R/svi_download.R")
source("./R/svi_clean_data.R")
source("./R/extract_counties_fips_from_svi.R")
source("./R/covid_download_data.R")
source("./R/covid_clean_data.R")
